//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwsiApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd1Entities2 : DbContext
    {
        public bd1Entities2()
            : base("name=bd1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BadanieTechniczne> BadanieTechnicznes { get; set; }
        public virtual DbSet<DowodRejestracyjny> DowodRejestracyjnies { get; set; }
        public virtual DbSet<KartaPojazdu> KartaPojazdus { get; set; }
        public virtual DbSet<Marka> Markas { get; set; }
        public virtual DbSet<Miejscowosc> Miejscowoscs { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Pojazd> Pojazds { get; set; }
        public virtual DbSet<Policjant> Policjants { get; set; }
        public virtual DbSet<RodzajPaliwa> RodzajPaliwas { get; set; }
        public virtual DbSet<TypNadwozia> TypNadwozias { get; set; }
        public virtual DbSet<Urzednik> Urzedniks { get; set; }
        public virtual DbSet<Uzytkownik> Uzytkowniks { get; set; }
        public virtual DbSet<Wojewodztwo> Wojewodztwoes { get; set; }
        public virtual DbSet<Wykroczenie> Wykroczenies { get; set; }
        public virtual DbSet<Powiat> Powiats { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
