//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwsiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pojazd
    {
        public string VIN { get; set; }
        public string idKartyPojazdu { get; set; }
        public Nullable<System.DateTime> dataAktualnegoDR { get; set; }
        public Nullable<int> ostatniZarejestrowanyStanLicznika { get; set; }
        public Nullable<bool> zarejestrowany { get; set; }
        public Nullable<bool> kradziony { get; set; }
    }
}
