//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwsiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Powiat
    {
        public int idPowiat { get; set; }
        public int idWojewodztwo { get; set; }
        public string powiat1 { get; set; }
    }
}
