//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwsiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypNadwozia
    {
        public int idTypNadwozia { get; set; }
        public string typNadwozia1 { get; set; }
    }
}
